project_id = "fttbwjuaaltomksuslyi"

[functions.auto-complete-bookings]
verify_jwt = false

[functions.rate-limiter]
verify_jwt = false

[functions.recalculate-ratings]
verify_jwt = false

[functions.tinkoff-payment-init]
verify_jwt = false

[functions.tinkoff-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = true

[functions.create-telegram-link-token]
verify_jwt = true

[functions.send-telegram-notification]
verify_jwt = true

[functions.send-my-telegram-test]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false
