project_id = "fttbwjuaaltomksuslyi"

[functions.auto-complete-bookings]
verify_jwt = false

[functions.rate-limiter]
verify_jwt = false

[functions.recalculate-ratings]
verify_jwt = false

[functions.tinkoff-payment-init]
verify_jwt = false

[functions.tinkoff-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = true
