// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttbwjuaaltomksuslyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGJ3anVhYWx0b21rc3VzbHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NjU4ODIsImV4cCI6MjA4NTA0MTg4Mn0.HSTrDQgTwr3m0NBX6j2qtPNDCLa_KhUyLHsj1fQWPso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});